[package]
name = "agc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hound = { workspace = true }
hypr-data = { workspace = true }
rodio = { workspace = true }

[dependencies]
dagc = "0.1.1"
