on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  check-authorization:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    outputs:
      authorized: ${{ steps.check_team.outputs.result }}
    steps:
      - name: Check team membership
        id: check_team
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.teams.getMembershipForUserInOrg({
                org: 'fastrepl',
                team_slug: 'team',
                username: context.actor
              });
              return true;
            } catch {
              return false;
            }

  claude:
    needs: check-authorization
    if: needs.check-authorization.outputs.authorized == 'true'
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dprint
        shell: bash
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh > /dev/null 2>&1
          echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          additional_permissions: "actions: read"
          model: "claude-opus-4-1-20250805"
          trigger_phrase: "@claude"
          allowed_tools: "Bash(pnpm install),Bash(cargo check --all-targets),Bash(dprint fmt)"
