on:
  workflow_dispatch:

jobs:
  sign-passthrough:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build

      - uses: ./.github/actions/apple_cert
        id: apple-cert
        with:
          apple-certificate: ${{ secrets.APPLE_CERTIFICATE }}
          apple-certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Compile and sign passthrough binary
        env:
          CERT_ID: ${{ steps.apple-cert.outputs.cert-id }}
        run: |
          swiftc scripts/passthrough.swift -o build/hyprnote-passthrough
          codesign -s "$CERT_ID" build/hyprnote-passthrough

          # Verify signing
          codesign -dv build/hyprnote-passthrough

          # Verify team identifier is correct
          if ! codesign -dv build/hyprnote-passthrough 2>&1 | grep -q "TeamIdentifier=6SLY7V277V"; then
            echo "Error: Binary not signed with correct team identifier (6SLY7V277V)"
            exit 1
          fi
          echo "✓ Binary signed with correct team identifier"

      - uses: actions/upload-artifact@v4
        with:
          name: hyprnote-passthrough-${{ github.sha }}
          path: |
            build/hyprnote-passthrough
          retention-days: 7
